version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: luxgame
      MYSQL_USER: user
      MYSQL_PASSWORD: user